select
CONVERT(date, GETDATE()) AS FechaHoy,
td.Fecha_actualizacion as Fecha_revision_variable,
td.Sku,
td.Sap,
td.Ordenado_LW,
td.Recibido_LWTOP,
td.Pedido_NS,
td.Surtido_NS,
td.Dbe_Pzas,
td.Venta_prom,
td.Venta_Semana_Anterior,
td.Forecast_Semana_Anterior,
td.Forecast_Semana_prox,
td.Forecast_SemanaN2,
td.Forecast_SemanaN3,
td.Recs_Semana_prox,
td.Recs_Semana_N2,
td.Recs_Semana_N3,
td.Recomedacion_logistica,
td.Volumen_semanal_promedioKG,
td.Merma_semanal_promedioKG,
td.Clase_merma,
td.Forecast_Accy,
td.Tipo_Accy
from mermas_autos_ItemReview_TD td